---
  name: 04 - Using Actions
  on: push
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
        - uses: actions/checkout@v4
        - name: Printing Folder
          run: ls

      # checkout the code from the repository 
      # 1. Install deps of our react application 
      # 2. Excute automated testssh
